spring.application.name=englearn
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=englearn
spring.datasource.username=postgres
spring.datasource.password=123456

jwt.signerKey=7wQK6kg246sTd4fxkSemp4AAxBpTflWtl6cEuyPmJJrtSSatmqEtrGRqQCYrGvji
jwt.valid-duration=3600
jwt.refreshable-duration=360000

fe.url=http://localhost:3000

cloudinary.cloud-name=dliqrd8zk
cloudinary.api-key=869661429583957
cloudinary.api-secret=eMHUI0xQez8y88sYpnF2448x_Nw

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Enable Spring Cache
spring.cache.type=redis

#email
spring.sendgrid.api-key=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


